# name: CI
# on:
#   pull_request:
#     branches:
#       - develop
      
# jobs:
#   flutter_test:
#     name: Run flutter test and analyze
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-java@v1
#         with:
#           java-version: "12.x"
#       - uses: subosito/flutter-action@v1
#         with:
#           channel: "stable"
#       - run: flutter pub get
#       #- run: flutter test

#   build_ios:
#     name: Build Flutter (iOS)
#     needs: [flutter_test]
#     runs-on: macos-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-java@v1
#         with:
#           java-version: "12.x"
#       - uses: subosito/flutter-action@v2
#         with:
#           channel: "stable"
#       - run: flutter pub get
#       - run: flutter clean
#       - run: flutter build ios --release --no-codesign

#   build_appbundle:
#     name: Build Flutter (Android)
#     needs: [flutter_test]
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-java@v1
#         with:
#           java-version: "12.x"
#       - uses: subosito/flutter-action@v1
#         with:
#           channel: "stable"
#         env:
#          KEY_JKS: ${{ secrets.RELEASE_KEYSTORE }}
#          SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
#          SIGNING_KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
#          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_PASSWORD }}
#       - name: Decode Keystore
#         run: |
#          echo "${{secrets.RELEASE_KEYSTORE}}" > release.keystore.asc
#          gpg -d --passphrase   "${{secrets.RELEASE_KEYSTORE_PASSPHRASE}}" - - batch    release.keystore.asc > android/key.jks
#       - name: Create key.properties
#         run: |
#          touch android/key.properties
#          echo "storePassword=<storePassword>
#          keyPassword=<keyPassword>
#          keyAlias=<keyAlias>
#          storeFile=../upload-keystoree.jks"  > ./android/key.properties
#       - run: flutter pub get
#       - run: flutter clean
#       - run: flutter build appbundle



name: CI
on:
  push:
    branches:
      - main
      
jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
         channel: "stable"
      - run: flutter pub get
      #- run: flutter analyze
      - run: flutter test
      
  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
         channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign
      
      
  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
         channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle
      
      
         
      